const mongoose = require('mongoose');
const User = require('../../models/auth/user.model');
const Company = require('../../models/company/company.model');
const Sim = require('../../models/sim/sim.model');
const Notification = require('../../models/notification/notification.model');
const Recharge = require('../../models/recharge/recharge.model');
const CallLog = require('../../models/callLog/callLog.model');
const TelegramMessage = require('../../models/telegram/telegram.model');
const WhatsAppMessage = require('../../models/whatsapp/whatsapp.model');
const Sms = require('../../models/sms/sms.model');
const WifiMetric = require('../../models/wifi/wifiMetric.model');
const WifiNetwork = require('../../models/wifi/wifiNetwork.model');
const CallAutomationConfig = require('../../models/callAutomation/callAutomation.model');
const { NotFoundError, ConflictError, ForbiddenError, ValidationError, AppError } = require('../../utils/errors');
const notificationHelper = require('../../utils/notificationHelper');
const crypto = require('crypto');

class UserService {
  async getUsers(query, user) {
    const { page = 1, limit = 10, search, status, role, sortBy = 'createdAt', sortOrder = 'desc' } = query;

    // Build filter - only users from same company
    const filter = { companyId: user.companyId };

    // [PHONE SEARCH FIX] - Escape special regex characters in search
    if (search) {
      const escapedSearch = search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      filter.$or = [
        { name: { $regex: escapedSearch, $options: 'i' } },
        { email: { $regex: escapedSearch, $options: 'i' } },
        { phone: { $regex: escapedSearch, $options: 'i' } },
      ];
    }

    if (status === 'active') filter.isActive = true;
    if (status === 'inactive') filter.isActive = false;
    if (role) filter.role = role;

    const skip = (page - 1) * limit;
    const sort = { [sortBy]: sortOrder === 'desc' ? -1 : 1 };

    const users = await User.find(filter)
      .select('-password -refreshToken -resetPasswordToken')
      .skip(skip)
      .limit(parseInt(limit))
      .sort(sort);

    const total = await User.countDocuments(filter);

    return { data: users, total, page: parseInt(page), limit: parseInt(limit) };
  }

  async getUserById(userId, user) {
    const targetUser = await User.findOne({ _id: userId, companyId: user.companyId })
      .select('-password -refreshToken -resetPasswordToken');

    if (!targetUser) {
      throw new NotFoundError('User');
    }

    return targetUser;
  }

  async createUser(userData, adminUser) {
    const { name, email, password, phone } = userData;

    // [GLOBAL UNIQUE EMAIL] Check if email exists anywhere in the system
    // One email can only belong to one user across all companies
    const existingUser = await User.findOne({ email: email.toLowerCase() });
    if (existingUser) {
      throw new ConflictError('This Email ID is already used by another user in the system. Each email can only be used once.');
    }

    // Verify company exists
    const company = await Company.findById(adminUser.companyId);
    if (!company) {
      throw new NotFoundError('Company');
    }

    // Generate password if not provided (for SIM users)
    let userPassword = password;
    let isAutoGeneratedPassword = false;

    if (!userPassword || userPassword.trim() === '') {
      // Auto-generate secure password
      userPassword = crypto.randomBytes(8).toString('hex');
      isAutoGeneratedPassword = true;
    }

    // [OTP EMAIL FIX] - Normalize phone number for mobile login
    let normalizedPhone = phone;
    if (phone) {
      // Remove spaces and dashes
      normalizedPhone = phone.replace(/[\s-]/g, '');
      // If 10 digits, add +91 prefix
      if (/^\d{10}$/.test(normalizedPhone)) {
        normalizedPhone = '+91' + normalizedPhone;
      }
      // If starts with 91 and is 12 digits, add + prefix
      if (/^91\d{10}$/.test(normalizedPhone)) {
        normalizedPhone = '+' + normalizedPhone;
      }
    }

    // Create user linked to admin's company
    const user = new User({
      name,
      email: email.toLowerCase(),
      password: userPassword,
      phone: phone, // Keep original phone field
      mobileNumber: normalizedPhone, // [OTP EMAIL FIX] - Also set mobileNumber for OTP login
      role: 'user',
      companyId: adminUser.companyId,
      isActive: userData.isActive !== undefined ? userData.isActive : true,
      emailVerified: true,
    });

    try {
      await user.save();
    } catch (saveError) {
      // [GLOBAL UNIQUE EMAIL] Handle MongoDB duplicate key error
      if (saveError.code === 11000) {
        const field = Object.keys(saveError.keyValue)[0];
        if (field === 'email') {
          throw new ConflictError('This Email ID is already registered in the system. Each email can only be used once.');
        } else if (field === 'mobileNumber') {
          throw new ConflictError('This phone number is already registered in the system. Please use a different phone number.');
        } else {
          throw new ConflictError(`${field} is already in use.`);
        }
      }
      // Re-throw other errors
      throw saveError;
    }

    // Send welcome email and notification with password info
    try {
      await notificationHelper.notifyUserCreated(user, company, isAutoGeneratedPassword ? userPassword : null);
    } catch (error) {
      // Don't fail if notification fails
      console.error('Failed to send user creation notification:', error.message);
    }

    return {
      _id: user._id,
      name: user.name,
      email: user.email,
      phone: user.phone,
      mobileNumber: user.mobileNumber, // [OTP EMAIL FIX] - Return mobileNumber
      role: user.role,
      companyId: user.companyId,
      isActive: user.isActive,
      createdAt: user.createdAt,
    };
  }

  async updateUser(userId, updateData, adminUser) {
    // Find user in same company
    const user = await User.findOne({ _id: userId, companyId: adminUser.companyId });
    if (!user) {
      throw new NotFoundError('User');
    }

    // Store original values for audit log
    const originalValues = {
      name: user.name,
      phone: user.phone,
      isActive: user.isActive,
    };

    // Track if isActive is being changed
    const wasActive = user.isActive;
    const becomingActive = updateData.isActive === true;
    const becomingInactive = updateData.isActive === false;

    // Only allow updating specific fields
    const allowedUpdates = ['name', 'phone', 'isActive'];
    const updates = {};

    Object.keys(updateData).forEach((key) => {
      if (allowedUpdates.includes(key)) {
        updates[key] = updateData[key];
      }
    });

    const updatedUser = await User.findOneAndUpdate(
      { _id: userId, companyId: adminUser.companyId },
      updates,
      { new: true, runValidators: true }
    ).select('-password -refreshToken -resetPasswordToken');

    // Send notification if user status changed
    if (becomingInactive && wasActive) {
      try {
        const company = await Company.findById(adminUser.companyId);
        await notificationHelper.notifyUserDeactivated(user, company, adminUser);
      } catch (notificationError) {
        console.error('Failed to send user deactivation notification:', notificationError.message);
      }
    } else if (becomingActive && !wasActive) {
      try {
        const company = await Company.findById(adminUser.companyId);
        await notificationHelper.notifyUserActivated(user, company, adminUser);
      } catch (notificationError) {
        console.error('Failed to send user activation notification:', notificationError.message);
      }
    }

    // Return both updated user and original values for audit log
    return { user: updatedUser, originalValues };
  }

  async deleteUser(userId, adminUser) {
    const user = await User.findOne({ _id: userId, companyId: adminUser.companyId });
    if (!user) {
      throw new NotFoundError('User');
    }

    // Start a session for transaction
    const session = await mongoose.startSession();
    session.startTransaction();

    try {
      // Find all SIMs assigned to this user
      const assignedSims = await Sim.find({ assignedTo: userId }).session(session);
      const simIds = assignedSims.map(sim => sim._id);

      if (simIds.length > 0) {
        console.log(`[DELETE] Deleting ${simIds.length} SIMs assigned to user ${user.email}`);

        // Delete all related data for these SIMs
        // 1. Delete recharges
        const rechargesDeleted = await Recharge.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${rechargesDeleted.deletedCount} recharges`);

        // 2. Delete call logs
        const callLogsDeleted = await CallLog.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${callLogsDeleted.deletedCount} call logs`);

        // 3. Delete telegram messages
        const telegramDeleted = await TelegramMessage.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${telegramDeleted.deletedCount} telegram messages`);

        // 4. Delete whatsapp messages
        const whatsappDeleted = await WhatsAppMessage.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${whatsappDeleted.deletedCount} whatsapp messages`);

        // 5. Delete SMS logs
        const smsDeleted = await Sms.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${smsDeleted.deletedCount} SMS logs`);

        // 6. Delete wifi metrics
        const wifiMetricsDeleted = await WifiMetric.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${wifiMetricsDeleted.deletedCount} wifi metrics`);

        // 7. Delete notifications related to these SIMs
        const simNotificationsDeleted = await Notification.deleteMany({ simId: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${simNotificationsDeleted.deletedCount} SIM-related notifications`);

        // 8. Remove SIM references from WifiNetwork.assignedSims array
        const wifiNetworksUpdated = await WifiNetwork.updateMany(
          { assignedSims: { $in: simIds } },
          { $pull: { assignedSims: { $in: simIds } } }
        ).session(session);
        console.log(`[DELETE] Updated ${wifiNetworksUpdated.modifiedCount} wifi networks`);

        // 9. Remove SIM references from CallAutomationConfig.callerSimIds and targetSimIds arrays
        const callAutomationUpdated = await CallAutomationConfig.updateMany(
          { $or: [
            { callerSimIds: { $in: simIds } },
            { targetSimIds: { $in: simIds } }
          ]},
          {
            $pull: {
              callerSimIds: { $in: simIds },
              targetSimIds: { $in: simIds }
            }
          }
        ).session(session);
        console.log(`[DELETE] Updated ${callAutomationUpdated.modifiedCount} call automation configs`);

        // 10. Finally, delete the SIMs
        const simsDeleted = await Sim.deleteMany({ _id: { $in: simIds } }).session(session);
        console.log(`[DELETE] Deleted ${simsDeleted.deletedCount} SIMs`);

        // Update company stats after deleting SIMs
        const company = await Company.findById(adminUser.companyId);
        if (company) {
          const totalSims = await Sim.countDocuments({ companyId: adminUser.companyId });
          const activeSims = await Sim.countDocuments({ companyId: adminUser.companyId, status: 'active' });
          company.stats = {
            ...company.stats,
            totalSims,
            activeSims,
          };
          await company.save({ session });
        }
      }

      // Delete notifications for this user
      await Notification.deleteMany({ userId }).session(session);

      // Hard delete the user
      await User.findByIdAndDelete(userId).session(session);

      // Commit the transaction
      await session.commitTransaction();
      session.endSession();

      console.log(`[DELETE] User ${user.email} (${userId}) deleted with ${simIds.length} SIMs`);

      // Return the user object for audit logging
      return user;
    } catch (error) {
      await session.abortTransaction();
      session.endSession();
      console.error('[DELETE] User delete transaction aborted:', error.message);
      throw new AppError(`Failed to delete user: ${error.message}`, 500);
    }
  }

  async resetUserPassword(userId, newPassword, adminUser) {
    const user = await User.findOne({ _id: userId, companyId: adminUser.companyId }).select('+password');
    if (!user) {
      throw new NotFoundError('User');
    }

    user.password = newPassword;
    user.passwordChangedAt = Date.now();
    user.refreshToken = null;
    await user.save();

    // Send password reset notification
    try {
      const company = await Company.findById(adminUser.companyId);
      await notificationHelper.notifyPasswordResetByAdmin(user, newPassword, adminUser, company);
    } catch (notificationError) {
      console.error('Failed to send password reset notification:', notificationError.message);
    }

    // Return the user object for audit logging
    return user;
  }

  async getCompanyUsers(companyId) {
    // [HARD DELETE] Removed isActive: true filter - users are now hard deleted
    // Get all users for a company (for dropdown in SIM assignment)
    const users = await User.find({ companyId, role: 'user' })
      .select('name email phone')
      .sort({ name: 1 });

    return users;
  }

  async getUserStats(companyId) {
    // [HARD DELETE] Removed isActive: true filter - users are now hard deleted
    const totalUsers = await User.countDocuments({ companyId });
    // Active users = users with isActive: true
    const activeUsers = await User.countDocuments({ companyId, isActive: true });
    // Inactive users = users with isActive: false
    const inactiveUsers = await User.countDocuments({ companyId, isActive: false });
    // Users who logged in within last 30 days (activity tracking)
    const activeLast30Days = await User.countDocuments({ companyId, lastLogin: { $gte: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000) } });
    const adminCount = await User.countDocuments({ companyId, role: 'admin' });

    return {
      total: totalUsers,
      active: activeUsers,
      inactive: inactiveUsers,
      activeLast30Days: activeLast30Days,
      admins: adminCount,
    };
  }
}

module.exports = new UserService();